// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaZv-n1HpXgWpoaQciGwbnuy6qdjvQPUs',
    appId: '1:661467871902:web:98d98a4b7410affdb6198f',
    messagingSenderId: '661467871902',
    projectId: 'jelly-52e9c',
    authDomain: 'jelly-52e9c.firebaseapp.com',
    storageBucket: 'jelly-52e9c.firebasestorage.app',
    measurementId: 'G-ZDEKXEKJWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xOXeByvNltds0QXQV9BqxXv4flPw3O4',
    appId: '1:661467871902:android:c7f2825b6bedb3acb6198f',
    messagingSenderId: '661467871902',
    projectId: 'jelly-52e9c',
    storageBucket: 'jelly-52e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwViGniJmal1QP8osmL_1yXCJ3IMazq_0',
    appId: '1:661467871902:ios:b14e168f4b4640beb6198f',
    messagingSenderId: '661467871902',
    projectId: 'jelly-52e9c',
    storageBucket: 'jelly-52e9c.firebasestorage.app',
    iosBundleId: 'buunyan.game.jelly',
  );
}
